### ISSUE TITLE
Theater Save Demo file

### ISSUE THREAD

**Issue by ViktorSMI** [Ezz-lol/boiii-free#2]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

The game has a theater mode in which you can view completed battles. The current implementation of boiii services lacks the necessary components to save demo files. At the beginning of the match, the client calls service 58 (bdPooledStorage) and the recording of the demo stops at that point. 
It would be great to implement bdContentStreaming and bdPooledStorage or find another solution for saving demos.

The game calls 52 service bdTags to view saved demos, but it is not as important to the theater as recording.

**Comment by prophetl33t** [comment]
Sounds like a great feature!
