### ISSUE TITLE
Server not accepting usermaps using boiii

### ISSUE THREAD

**Issue by mandeel99** [Ezz-lol/boiii-free#21]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Linux

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. download a custommap using steamcmd and put it in the server files in usermaps (i put everything in just incase.)
2. Second not working entirely and just unable to connect to it and pumps out memory dumps
3. unable to play custom maps
4. 

### Expected Result

for it load The custom map!

### Actual Result

nothing unable to connect to it even after putting the ip

### Severity/Priority

Medium

**Comment by Skwll** [comment]
Boiii does accept usermaps
![image](https://github.com/Ezz-lol/boiii-free/assets/63907514/7212f024-6c38-4757-a2ae-18631ff135b0)

Make sure you edit the according cfg file & have the correct folder structure
![image](https://github.com/Ezz-lol/boiii-free/assets/63907514/d3c6889b-56f8-493a-82df-075509da1b2d)
![image](https://github.com/Ezz-lol/boiii-free/assets/63907514/c96cf43b-c095-4fb8-8768-3e7e7cf237e4)

(if you're using the current pterodactyl egg for boiii then you're probably missing some needed zm fastfiles in your zone folder)
