### ISSUE TITLE
Splitscreen Online

### ISSUE THREAD

**Issue by Zaybomb** [Ezz-lol/boiii-free#23]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

If you try to use splitscreen online, it loads halfway and then returns to the menu. It only says Error.

### Expected Result

I would love to be able to use split screen online since I have two PCs and my brother my dad and I would like to play together.

### Actual Result

It says Error.

### Severity/Priority

High/Critical

**Comment by Zaybomb** [comment]
> Ok, I figured it out, you might want to make this a guide. Basically, the pc with 2 players runs ipconfig in cmd, finds their ip. They the start up a private game and set it to un-ranked. After that, the other pc uses ~connect ( 2 player pc ip)

**Comment by sherlock-james** [comment]
have you found any way to actually join any other dedicated server ?
( i know you can host and others join , but have you found a way to join the online public dedicated servers through the split-screen mode?
